### ISSUE TITLE
Flaw in demo.v.

### ISSUE THREAD

**Issue by sighingnow** [hengruoz/hengruoz.github.io#1]
Hi, I have read your blog about how to write a Coq plugin in OCaml. The usage of tactics in plugin seems incorrect in demo.v (maybe just a clerical error). The original code doesn't work with Coq 8.5 lp3 on my Ubuntu 16.04. It seems that `killtrans` should be used in the proofs rather than `myplugin`. I think `myplugin` is not a tactic. We can use the new tactic as:

~~~coq
Declare ML Module "myplugin".

Theorem trans_imply_3: forall P1 P2 P3:Prop,
(P1 -> P2) -> (P2 -> P3) -> (P1 -> P3).
Proof.
  killtrans.
Qed.
~~~

Please notice that the original proof in demo.v is:

~~~coq
Proof.
  myplugin.
Qed.
~~~

**Comment by hengruoz** [comment]
You are right. Thank you very much!
